# Chapter 3 - Tensors

Learning Outcomes:
- Understand tensors and basic datastructure within PyTorch
- Indexing and operating tensors
- Interoperating with NumPy multidimensional arrays
- Using GPU for computations and speed

Summary:
- Neural nets turn floating points into other floating point representations. Can be seen by humans and interpreted but the transition cant really be interpreted
- Floating points stored in tensors
- Tensors are multidimensional arrays, core datastructure in PyTorch
- PyTorch includes all you need to deal with tensors
- Serialised to disks and loaded back
- Cna run on CPU and GPU
- Trailing udnerscore to operate on tensors

Things To Look Out For:
- Creating and using tensors
- Different tensor opperations

### 3.1 - Floating Point Numbers

- Tensors are the generalisation of vectors to an arbitrary amount of dimensions
- Multidimensional array
PyTorch uses NumPy, SciPy, Pandas, and Sci-kit learn

### 3.2 - Tensors: Multidimensional Arrays
- Lists to PyTorch Tensors

In [1]:
a = [1.0, 2.0, 1.0]
a[0]

1.0

In [2]:
import torch
a = torch.ones(3) #creates a tensor of 3 ones
a

tensor([1., 1., 1.])

In [3]:
a[2]
a[2] = 2 #Changing values in the tensor

In [4]:
a[2]

tensor(2.)

In [5]:
#The below example is for a triangle with the points as their 2D coordinates
points = torch.zeros(6)
points[0] = 4.0
points[1] = 1.0
points[2] = 5.0
points[3] = 2.0
points[4] = 2.0
points[5] = 1.0
points 

tensor([4., 1., 5., 2., 2., 1.])

In [6]:
#The below is the same as the above
points = torch.tensor([4.0, 1.0, 5.0, 3.0, 2.0, 1.0])
points

tensor([4., 1., 5., 3., 2., 1.])

In [7]:
#Each coordinate would be like the following
(float(points[0]), float(points[1]))

(4.0, 1.0)

In [8]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points, points.shape

(tensor([[4., 1.],
         [5., 3.],
         [2., 1.]]),
 torch.Size([3, 2]))

In [9]:
#Method above is quite convoluted, can do the below
points = torch.zeros(3, 2)
points

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [10]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [11]:
points[0, 1], points[0]

(tensor(1.), tensor([4., 1.]))

- Tensors store data more efficiently and in one area as opposed to lists
- Indexing methods below

In [12]:
points[1:], points[1:,:], points[1:,0], points[None]

(tensor([[5., 3.],
         [2., 1.]]),
 tensor([[5., 3.],
         [2., 1.]]),
 tensor([5., 2.]),
 tensor([[[4., 1.],
          [5., 3.],
          [2., 1.]]]))

In [13]:
img_t = torch.randn(3, 5, 5) #Channels, rows, columns, 3 dimensions?
weights = torch.tensor([0.2126, 0.7152, 0.0722])

img_t, img_t.shape, weights

(tensor([[[ 1.2764e+00, -1.8891e+00,  2.5663e+00,  7.8000e-01,  1.8298e-02],
          [-9.5934e-02,  7.0364e-01,  1.3453e+00,  7.9081e-01,  8.1403e-01],
          [-1.0623e+00, -1.2951e+00, -7.2420e-01, -1.1008e+00,  5.6799e-01],
          [ 6.5098e-01,  3.3948e-01,  1.7156e-01, -2.9337e-01, -1.2991e-01],
          [-5.5935e-01, -2.3687e-03, -3.4211e-01, -1.9345e+00,  8.6455e-02]],
 
         [[ 1.7119e+00,  8.8456e-01,  1.9680e+00, -1.4753e+00,  6.5083e-01],
          [ 1.0845e+00,  6.4771e-01, -4.9513e-01, -1.3086e+00, -6.6175e-02],
          [ 6.9321e-02,  1.3540e-01, -5.7981e-01, -1.5813e-01, -1.0391e+00],
          [ 3.2854e-01,  3.2642e-01, -9.5890e-01,  5.7654e-01,  2.0980e-02],
          [-2.2071e-01,  8.7300e-01,  2.0059e+00,  1.3835e-01, -1.2173e-01]],
 
         [[ 2.9886e-01,  1.4612e+00,  2.2837e-01,  6.0616e-01, -1.1273e+00],
          [-9.4239e-01, -2.1020e+00,  1.0691e+00,  1.1302e-01,  3.2141e-01],
          [-3.9510e-02,  4.8467e-01,  4.8397e-01, -7.1440e-01,  2.3843

In [14]:
batch_t = torch.randn(2, 3, 5, 5) #shape [batch, channels, rows, columns]
batch_t[0] #Splits it into batches which can be easier for the data to be processed by the neural network
#Batches are also really useful for use with GPU's

tensor([[[-1.3139,  0.9065, -2.0794, -0.4127, -1.1388],
         [-0.9820, -0.2699, -0.3858, -0.4354,  0.9286],
         [-0.0916, -0.5251,  1.4709, -1.8182, -0.5707],
         [-0.8443, -0.3540,  0.2046,  0.8712, -0.2835],
         [ 0.0639,  0.6626,  0.4145, -0.5431,  0.0250]],

        [[-0.2236, -1.5097, -0.9841, -1.1071, -0.6928],
         [-0.4414, -0.2183,  0.0961,  1.4813, -1.7205],
         [-0.4203,  0.6960, -0.2698,  1.3844,  1.0403],
         [-1.5784,  0.8017,  0.1664, -1.1519, -0.3867],
         [-0.0133, -0.3662, -2.2483, -0.2246,  1.6467]],

        [[ 0.6792,  0.6136,  1.6586,  0.1744,  1.2825],
         [ 0.4921, -3.1010, -0.7434, -1.5832,  1.0970],
         [ 1.3099, -0.1467,  0.0486, -0.2931, -0.5044],
         [ 1.4283,  0.9263, -0.3370, -1.1557, -0.1936],
         [ 0.6499,  0.4755,  1.5617,  0.1628,  0.7567]]])

In [15]:
img_gray_naive = img_t.mean(-3)
batch_gray_naive = batch_t.mean(-3) #Generalise based on the different shapes
img_gray_naive.shape, batch_gray_naive.shape

(torch.Size([5, 5]), torch.Size([2, 5, 5]))

In [16]:
#Broadcasting takes smaller tensors and changes the shapes so that you can do element wise operations between tensors
unsqueezed_weights = weights.unsqueeze(-1).unsqueeze(-1)
img_weights = (img_t * unsqueezed_weights)
batch_weights = (batch_t * unsqueezed_weights)
img_gray_weighted = img_weights.sum(-3)
batch_gray_weighted = batch_weights.sum(-3)
batch_weights.shape, batch_t.shape, unsqueezed_weights.shape

(torch.Size([2, 3, 5, 5]), torch.Size([2, 3, 5, 5]), torch.Size([3, 1, 1]))

In [17]:
#Einsum can do the same
img_gray_weighted_fancy = torch.einsum('...chw,c->...hw', img_t, weights)
batch_gray_weighted_fancy = torch.einsum('...chw,c->...hw', batch_t, weights)
batch_gray_weighted_fancy

tensor([[[-0.3902, -0.8427, -1.0262, -0.8669, -0.6450],
         [-0.4890, -0.4374, -0.0670,  0.8526, -0.9539],
         [-0.2255,  0.3756,  0.1233,  0.5824,  0.5863],
         [-1.2053,  0.5650,  0.1382, -0.7221, -0.3508],
         [ 0.0510, -0.0867, -1.4071, -0.2644,  1.2377]],

        [[ 0.8797, -0.1352,  0.0755,  0.1206,  0.1605],
         [ 1.6362,  0.5831,  0.1041, -0.6521, -0.0454],
         [-0.1227, -0.2197, -0.6143, -0.0905,  0.3554],
         [ 0.1721, -0.1028, -0.2085, -0.3397,  2.4509],
         [-1.4506, -1.9501,  0.4921, -0.8770,  0.0469]]])

In [18]:
#Can name the dimensions
weights_named = torch.tensor([0.2126, 0.7152, 0.0722], names=["channels"])
weights_named

/var/folders/cy/8tk4c03d6td9nktt82r_rb380000gn/T/ipykernel_37014/3551129751.py:2: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/c10/core/TensorImpl.h:1928.)
  weights_named = torch.tensor([0.2126, 0.7152, 0.0722], names=["channels"])


tensor([0.2126, 0.7152, 0.0722], names=('channels',))

In [19]:
#Use refine names to not change existing ones
img_named = img_t.refine_names(..., "channels", "rows", "columns")
batch_named = batch_named = batch_t.refine_names(..., "channels", "rows", "columns")
print("img named:", img_named.shape, img_named.names)
print("batch named:", batch_named.shape, batch_named.names)

img named: torch.Size([3, 5, 5]) ('channels', 'rows', 'columns')
batch named: torch.Size([2, 3, 5, 5]) (None, 'channels', 'rows', 'columns')


In [20]:
#Align_as takes care of the missing dimensions not taken care of
weights_aligned = weights_named.align_as(img_named)
weights_aligned.shape, weights_aligned.names

(torch.Size([3, 1, 1]), ('channels', 'rows', 'columns'))

In [21]:
#If you want to sum on the channels dimensions
gray_named = (img_named * weights_aligned).sum('channels')
gray_named.shape, gray_named.names

(torch.Size([5, 5]), ('rows', 'columns'))

In [22]:
gray_named = (img_named[...,:3] * weights_named).sum("channels") #Cannot since they are of different dimensions and channels is not in the same locations

RuntimeError: Error when attempting to broadcast dims ['channels', 'rows', 'columns'] and dims ['channels']: dim 'columns' and dim 'channels' are at the same position from the right but do not match.

In [23]:
gray_plain = gray_named.rename(None)
gray_plain.shape, gray_plain.names #names have been renamed to none

(torch.Size([5, 5]), (None, None))

- Must specify the data type in the tensors so that computations can be done efficiently
- Most time spent on float32 and int64

In [24]:
#Can specify the datatype as an argument
double_points = torch.ones(10, 2, dtype=torch.double)
short_points = torch.tensor([[1, 2], [3, 4]], dtype=torch.short)
short_points.dtype, double_points.dtype

(torch.int16, torch.float64)

In [25]:
double_points = torch.zeros(10, 2).double()
short_points = torch.ones(10, 2).short()

In [26]:
#To as a converter
double_points = torch.zeros(10, 2).to(torch.double)
short_points = torch.ones(10, 2).to(dtype=torch.short)

In [27]:
#Need to make sure if there is a computation between tensors
points_64 = torch.rand(5, dtype=torch.double) #random tensor of size 5 containing numbers from 0 to 1
points_short = points_64.to(dtype=torch.short)
points_64 * points_short

tensor([0., 0., 0., 0., 0.], dtype=torch.float64)

In [28]:
a = torch.ones(3, 2)
a_t = torch.transpose(a, 0, 1)
a.shape, a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

Different tensor opperations
- Cteation ops - constructing tensors
- Indexing, slicing, joining, mutating ops - Changing shape, stride or content
- Math ops - pointwise, reduction, comparison, spectral

Indexing into storage

In [29]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points.storage() #This is how its stored

/var/folders/cy/8tk4c03d6td9nktt82r_rb380000gn/T/ipykernel_37014/3092447483.py:2: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  points.storage() #This is how its stored


 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [30]:
points_storage = points.storage()
points_storage[0] #Storage layout is always 1D, cannot be 2D

4.0

In [31]:
points_storage[0] = 2.0 #Changes the points.storage()
points

tensor([[2., 1.],
        [5., 3.],
        [2., 1.]])

In place operations include trailing __ that show that it replaces not makes a new one

In [32]:
a = torch.ones(3, 2)
a.zero_()
a #Didnt have to assing a.zero_() to another variable

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [33]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1]
second_point.storage_offset() #Shows the number of storage elements before you get to the one you are on

2

In [34]:
second_point.size(), second_point.shape

(torch.Size([2]), torch.Size([2]))

In [35]:
points.stride() #Need to go 2 across and one down

(2, 1)

In [36]:
#Not always desirable to change the original tensor, can clone
second_point  = points[1].clone()
second_point[0] = 10.0
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [37]:
#Transposing without copying
points_t = points.t()
points_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [38]:
#Showing that two tensors share the same storage (i.e, not coppied)
id(points.storage()) == id(points_t.storage())

True

In [39]:
#Only differe in shape and stride
points.stride()

(2, 1)

In [40]:
points_t.stride()

(1, 2)

##### Transposing in Higher Dimensions 

In [44]:
#Creating a high dimensional t ensore of ones, and transposing to specified shape
some_t = torch.ones(3, 4, 5)
transpose_t = some_t.transpose(0, 2) #Flips the shape and the strid
some_t.shape, some_t.stride()

(torch.Size([3, 4, 5]), (20, 5, 1))

In [45]:
transpose_t.shape, transpose_t.stride()

(torch.Size([5, 4, 3]), (1, 5, 20))

Overall, this improves the way that data is retrived making it more efficient

##### Contiguous Tensors
- Elements are laid out sequentially in memory, a lot more efficient as stated above. 

In [47]:
points.is_contiguous(), points_t.is_contiguous()

(True, False)

In [48]:
points = torch.tensor([[4.0, 1.0],[5.0, 3.0], [2.0, 1.0]])
points_t = points.t()
points_t, points_t.storage(), points_t.stride()

(tensor([[4., 5., 2.],
         [1., 3., 1.]]),
  4.0
  1.0
  5.0
  3.0
  2.0
  1.0
 [torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6],
 (1, 2))

In [50]:
# Making it a contiguous tensor
points_t_cont = points_t.contiguous() 
#Looking at the stride
points_t_cont, points_t_cont.stride(), points_t_cont.storage()

(tensor([[4., 5., 2.],
         [1., 3., 1.]]),
 (3, 1),
  4.0
  5.0
  2.0
  1.0
  3.0
  1.0
 [torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6])

##### Moving tensors to the GPU

In [54]:
points_gpu = points.to(device='mps') #Since apple doesnt support cuda, use the mps

In [56]:
points = 2 * points
points_gpu = 2 * points.to(device="mps")

In [57]:
points_gpu += 4

In [58]:
points_cpu = points_gpu.to(device="cpu")

##### NumPy Interoperability

In [59]:
#Turning pytorch tensor into a numpy array
points = torch.ones(3, 4)
points_np = points.numpy()
points_np

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [61]:
#Can turn a numpy array into a tensor
points = torch.from_numpy(points_np)
points

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

- Can also save tensors to a file and open it later if its really important using the load function and save